import 'package:mentor_me/services/services.dart';
import 'dart:core';

List<String> courses = [
  'EECE 101',
  'EGPP 101',
  'ENGW 101',
  'HIST 101',
  'COMM 101',
  'EECS 101',
  'CSCI 101',
  'EECE 101',
  'EGPP 101',
  'ENGW 101',
  'HIST 101',
  'COMM 101',
  'EECS 101',
  'CSCI 101',
  'EECE 101',
  'EGPP 101',
  'ENGW 101',
  'HIST 101',
  'COMM 101',
  'EECS 101',
  'CSCI 101',
  'EECE 101',
  'EGPP 101',
  'ENGW 101',
  'HIST 101',
  'COMM 101',
  'EECS 101',
  'CSCI 101',
];

Map<String, Map<String, dynamic>> test_posts = {
  '1': {
    'photoURL':
        'https://drive.google.com/uc?id=1sU9A3_w1i58aNAkEWNN1KTBKwYqvB9to',
    'userName': 'James Brown',
    'time': '12/31/2023 3:20pm',
    'content': 'Hello world, How are you guys?',
    'likes': 0,
    'comments': 0,
  },
  '2': {
    'photoURL':
        'https://drive.google.com/uc?id=1rFtFKrH_CxIbYcWw-8-uh8H2h0rjLpp-',
    'userName': 'Ruby Rose',
    'time': '12/31/2023 3:20pm',
    'content':
        'Meta is hiring! Use this link -> https://www.androidpolice.com/install-adb-windows-mac-linux-guide/',
    'likes': 0,
    'comments': 0,
  },
  '3': {
    'photoURL': 'https://picsum.photos/250?image=9',
    'userName': 'Mac Daniels',
    'time': '12/31/2023 1:20pm',
    'content':
        'Hello world, we are good and you?Hello world, we are good and you?Hello world, we are good and you?Hello world, we are good and you?Hello world, we are good and you?Hello world, we are good and you?Hello world, we are good and you?Hello world, we are good and you?Hello world, we are good and you?Hello world, we are good and you?Hello world, we are good and you?Hello world, we are good and you?',
    'likes': 0,
    'comments': 0,
  },
};

List<MyUser> test_users = [
  MyUser(
      uid: '1',
      email: 'allojeff',
      first_name: 'Jeff',
      last_name: 'Allo',
      school_id: 'Howard',
      faculty: 'CEA',
      department: 'Electrical',
      status: 'Mentor',
      year: 2),
  MyUser(
      uid: '1',
      email: 'allojeff',
      first_name: 'Jeff',
      last_name: 'Allo',
      school_id: 'Howard',
      faculty: 'CEA',
      department: 'Electrical',
      status: 'Mentor',
      year: 2,
      photoURL: 'https://picsum.photos/250?image=9'),
  MyUser(
      uid: '1',
      email: 'allojeff',
      first_name: 'Jeff',
      last_name: 'Allo',
      school_id: 'Howard',
      faculty: 'CEA',
      department: 'Electrical',
      status: 'Mentor',
      year: 2),
  MyUser(
      uid: '1',
      email: 'allojeff',
      first_name: 'Jeff',
      last_name: 'Allo',
      school_id: 'Howard',
      faculty: 'CEA',
      department: 'Electrical',
      status: 'Mentor',
      year: 2),
  MyUser(
      uid: '1',
      email: 'allojeff',
      first_name: 'Jeff',
      last_name: 'Allo',
      school_id: 'Howard',
      faculty: 'CEA',
      department: 'Electrical',
      status: 'Mentor',
      year: 2),
  MyUser(
      uid: '1',
      email: 'allojeff',
      first_name: 'Jeff',
      last_name: 'Allo',
      school_id: 'Howard',
      faculty: 'CEA',
      department: 'Electrical',
      status: 'Mentor',
      year: 2),
];
